language: php
php:
  - 5.5
  - hhvm
addons:
  code_climate:
    repo_token: a287a9f92ced095f4f2b73987bcb29e4e4efcf5435eb9958d5b55c4a4480320c

before_script:
  - composer self-update
  - composer install

script:
  - phpunit --coverage-clover build/logs/clover.xml
  - CODECLIMATE_REPO_TOKEN=a287a9f92ced095f4f2b73987bcb29e4e4efcf5435eb9958d5b55c4a4480320c ./vendor/bin/test-reporter