<div class="modal fade" tabindex="-1" role="dialog" id="postModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">New Comment</h4>
            </div>
            <form method="POST" action="{{ path_for('new_comment') }}">
            <div class="modal-body">
                <label for="comment">What do you want to say?</label>
                <textarea title="comment" id="comment" class="form-control" rows="3" name="comment" maxlength="1024"></textarea>

                <div class="form-group">
                    <label for="name">Author</label>
                    <input name="author" type="text" class="form-control" id="name" placeholder="Anonymous"/>
                </div>
                <div class="form-group">
                    <label for="secret">Secret</label>
                    <a tabindex="0" role="button" data-toggle="popover" data-trigger="focus" title="What is secret used for?" data-content="The secret is used to confirm the identity of the poster. It's not required but if you provide it readers will know content is really from you."><span class="badge" >?</span></a>

                    <input type="password" class="form-control" id="secret" placeholder="Secret" name="secret"/>
                </div>
                <div class="g-recaptcha" data-sitekey="6LdLwRITAAAAAB85c5mvM2S3b2onWewY2yOt_XdH"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
            </form>
        </div>
    </div>
</div>